// <auto-generated />
using System;
using Api_c_sharp.Models.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api_c_sharp.Migrations
{
    [DbContext(typeof(AutoPulseBdContext))]
    [Migration("20260105143014_CreationDB")]
    partial class CreationDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api_c_sharp.Models.Entity.APourConversation", b =>
                {
                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<int>("IdConversation")
                        .HasColumnType("integer")
                        .HasColumnName("con_id");

                    b.HasKey("IdCompte", "IdConversation");

                    b.HasIndex("IdConversation");

                    b.ToTable("t_j_apourconversation_apc", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.APourCouleur", b =>
                {
                    b.Property<int>("IdCouleur")
                        .HasColumnType("integer")
                        .HasColumnName("cou_id");

                    b.Property<int>("IdVoiture")
                        .HasColumnType("integer")
                        .HasColumnName("voi_id");

                    b.Property<int?>("voi_idcouleur")
                        .HasColumnType("integer");

                    b.HasKey("IdCouleur", "IdVoiture");

                    b.HasIndex("IdVoiture");

                    b.ToTable("t_j_apourcouleur_apc", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Adresse", b =>
                {
                    b.Property<int>("IdAdresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("adr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAdresse"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_codepostal");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<int>("IdPays")
                        .HasColumnType("integer")
                        .HasColumnName("pays_id");

                    b.Property<string>("LibelleVille")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_libelleville");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_nom");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("adr_numero");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_rue");

                    b.HasKey("IdAdresse");

                    b.HasIndex("IdCompte");

                    b.HasIndex("IdPays");

                    b.ToTable("t_e_adresse_adr", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Annonce", b =>
                {
                    b.Property<int>("IdAnnonce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ann_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnnonce"));

                    b.Property<DateTime?>("DatePublication")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ann_dat");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("ann_description");

                    b.Property<int>("IdAdresse")
                        .HasColumnType("integer")
                        .HasColumnName("adr_id");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<int>("IdEtatAnnonce")
                        .HasColumnType("integer")
                        .HasColumnName("eta_id");

                    b.Property<int>("IdMiseEnAvant")
                        .HasColumnType("integer")
                        .HasColumnName("mav_id");

                    b.Property<int>("IdVoiture")
                        .HasColumnType("integer")
                        .HasColumnName("voi_id");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ann_nom");

                    b.Property<int>("Prix")
                        .HasColumnType("integer")
                        .HasColumnName("ann_pri");

                    b.HasKey("IdAnnonce");

                    b.HasIndex("IdAdresse");

                    b.HasIndex("IdCompte");

                    b.HasIndex("IdMiseEnAvant");

                    b.HasIndex("IdVoiture");

                    b.HasIndex("IdEtatAnnonce", "DatePublication");

                    b.ToTable("t_e_annonce_ann", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Avis", b =>
                {
                    b.Property<int>("IdAvis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("avi_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAvis"));

                    b.Property<string>("ContenuAvis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("avi_libelle");

                    b.Property<DateTime>("DateAvis")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("avi_date");

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_idcommande");

                    b.Property<int>("IdJugee")
                        .HasColumnType("integer")
                        .HasColumnName("com_id_jugee");

                    b.Property<int>("IdJugeur")
                        .HasColumnType("integer")
                        .HasColumnName("com_id_jugeur");

                    b.Property<int>("NoteAvis")
                        .HasColumnType("integer")
                        .HasColumnName("avi_note");

                    b.HasKey("IdAvis");

                    b.HasIndex("IdCommande");

                    b.HasIndex("IdJugee");

                    b.HasIndex("IdJugeur");

                    b.ToTable("t_e_avis_avi", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Bloque", b =>
                {
                    b.Property<int>("IdBloque")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<int>("IdBloquant")
                        .HasColumnType("integer")
                        .HasColumnName("blo_id");

                    b.Property<DateTime>("DateBloque")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blo_date");

                    b.HasKey("IdBloque", "IdBloquant");

                    b.HasIndex("IdBloquant");

                    b.ToTable("t_j_bloque_blo", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.BoiteDeVitesse", b =>
                {
                    b.Property<int>("IdBoiteDeVitesse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("boi_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBoiteDeVitesse"));

                    b.Property<string>("LibelleBoite")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("boi_lib");

                    b.HasKey("IdBoiteDeVitesse");

                    b.ToTable("t_e_boitedevitesse_boi", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Carburant", b =>
                {
                    b.Property<int>("IdCarburant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCarburant"));

                    b.Property<string>("LibelleCarburant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("car_lib");

                    b.HasKey("IdCarburant");

                    b.ToTable("t_e_carburant_car", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.CarteBancaire", b =>
                {
                    b.Property<int>("IdCarteBancaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cba_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCarteBancaire"));

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cba_date_expiration");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_idcompte");

                    b.Property<string>("NumeroCarte")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cba_numero");

                    b.HasKey("IdCarteBancaire");

                    b.HasIndex("IdCompte");

                    b.ToTable("t_e_cartebancaire_cba", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Categorie", b =>
                {
                    b.Property<int>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategorie"));

                    b.Property<string>("LibelleCategorie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cat_lib");

                    b.HasKey("IdCategorie");

                    b.ToTable("t_e_categorie_cat", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cmd_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCommande"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cmd_date");

                    b.Property<int>("IdAcheteur")
                        .HasColumnType("integer")
                        .HasColumnName("com_id_acheteur");

                    b.Property<int>("IdAnnonce")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_id_annonce");

                    b.Property<int>("IdMoyenPaiement")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_moyen_paiement");

                    b.Property<int>("IdVendeur")
                        .HasColumnType("integer")
                        .HasColumnName("com_id_vendeur");

                    b.HasKey("IdCommande");

                    b.HasIndex("IdAcheteur");

                    b.HasIndex("IdAnnonce");

                    b.HasIndex("IdMoyenPaiement");

                    b.HasIndex("IdVendeur");

                    b.ToTable("t_e_commande_cmd", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Compte", b =>
                {
                    b.Property<int>("IdCompte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCompte"));

                    b.Property<bool>("A2fActif")
                        .HasColumnType("boolean")
                        .HasColumnName("com_a2f_actif");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("text")
                        .HasColumnName("com_auth_provider");

                    b.Property<string>("Biographie")
                        .HasColumnType("text")
                        .HasColumnName("com_biographie");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("com_date_creation");

                    b.Property<DateTime?>("DateDerniereActivationA2f")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("com_date_derniere_activation_a2f");

                    b.Property<DateTime>("DateDerniereConnexion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("com_date_derniere_connexion");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("com_date_naissance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("com_email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("com_google_id");

                    b.Property<int>("IdEtatCompte")
                        .HasColumnType("integer")
                        .HasColumnName("etc_id");

                    b.Property<int>("IdTypeCompte")
                        .HasColumnType("integer")
                        .HasColumnName("tco_id");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("com_mdp");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("com_nom");

                    b.Property<string>("NumeroSiret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpr_siret");

                    b.Property<string>("NumeroTelephone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("com_numero_telephone");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("com_prenom");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("com_pseudo");

                    b.Property<string>("RaisonSociale")
                        .HasColumnType("text")
                        .HasColumnName("cpr_raison_sociale");

                    b.HasKey("IdCompte");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdEtatCompte");

                    b.HasIndex("IdTypeCompte");

                    b.HasIndex("Pseudo")
                        .IsUnique();

                    b.ToTable("t_e_compte_com", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Conversation", b =>
                {
                    b.Property<int>("IdConversation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("con_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConversation"));

                    b.Property<DateTime>("DateDernierMessage")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("con_date_dernier_message");

                    b.Property<int>("IdAnnonce")
                        .HasColumnType("integer")
                        .HasColumnName("ann_id");

                    b.HasKey("IdConversation");

                    b.HasIndex("IdAnnonce");

                    b.ToTable("t_e_conversation_con", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Couleur", b =>
                {
                    b.Property<int>("IdCouleur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cou_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCouleur"));

                    b.Property<string>("CodeHexaCouleur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cou_codehexa");

                    b.Property<string>("LibelleCouleur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cou_lib");

                    b.HasKey("IdCouleur");

                    b.ToTable("t_e_couleur_cou", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.EtatAnnonce", b =>
                {
                    b.Property<int>("IdEtatAnnonce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("eta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEtatAnnonce"));

                    b.Property<string>("LibelleEtatAnnonce")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eta_lib");

                    b.HasKey("IdEtatAnnonce");

                    b.ToTable("t_e_etatannonce_eta", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.EtatCompte", b =>
                {
                    b.Property<int>("IdEtatCompte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("etc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEtatCompte"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etc_libelle");

                    b.HasKey("IdEtatCompte");

                    b.ToTable("t_e_etatcompte_etc", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.EtatSignalementPlainte", b =>
                {
                    b.Property<int>("IdEtatSignalement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ets_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEtatSignalement"));

                    b.Property<string>("LibelleEtatSignalement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eta_lib");

                    b.HasKey("IdEtatSignalement");

                    b.ToTable("t_e_etatsignalementplainte_ets", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Facture", b =>
                {
                    b.Property<int>("IdFacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fac_id");

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_id");

                    b.HasKey("IdFacture");

                    b.ToTable("t_e_facture_fac", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Favori", b =>
                {
                    b.Property<int>("IdAnnonce")
                        .HasColumnType("integer")
                        .HasColumnName("ann_id");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.HasKey("IdAnnonce", "IdCompte");

                    b.HasIndex("IdCompte");

                    b.ToTable("t_j_favori_fav", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Image", b =>
                {
                    b.Property<int>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdImage"));

                    b.Property<byte[]>("Fichier")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("img_fichier");

                    b.Property<int?>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<int?>("IdVoiture")
                        .HasColumnType("integer")
                        .HasColumnName("voi_id");

                    b.HasKey("IdImage");

                    b.HasIndex("IdCompte");

                    b.HasIndex("IdVoiture");

                    b.ToTable("t_e_image_img", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Journal", b =>
                {
                    b.Property<int>("IdJournal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("jou_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdJournal"));

                    b.Property<string>("ContenuJournal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jou_contenu");

                    b.Property<DateTime>("DateJournal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("jou_date");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<int>("IdTypeJournal")
                        .HasColumnType("integer")
                        .HasColumnName("tjo_id");

                    b.Property<int?>("IdTypeJournaux")
                        .HasColumnType("integer");

                    b.HasKey("IdJournal");

                    b.HasIndex("IdTypeJournal");

                    b.HasIndex("IdCompte", "DateJournal");

                    b.ToTable("t_e_journal_jou", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Marque", b =>
                {
                    b.Property<int>("IdMarque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mar_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMarque"));

                    b.Property<string>("LibelleMarque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mar_lib");

                    b.HasKey("IdMarque");

                    b.ToTable("t_e_marque_mar", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Message", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mes_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMessage"));

                    b.Property<string>("ContenuMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mes_contenu");

                    b.Property<DateTime>("DateEnvoiMessage")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mes_dateenvoi");

                    b.Property<bool>("EstLu")
                        .HasColumnType("boolean")
                        .HasColumnName("mes_estlu");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<int>("IdConversation")
                        .HasColumnType("integer")
                        .HasColumnName("con_id");

                    b.HasKey("IdMessage");

                    b.HasIndex("IdCompte");

                    b.HasIndex("IdConversation");

                    b.HasIndex("IdMessage", "DateEnvoiMessage");

                    b.ToTable("t_e_message_mes", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.MiseEnAvant", b =>
                {
                    b.Property<int>("IdMiseEnAvant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mav_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMiseEnAvant"));

                    b.Property<string>("LibelleMiseEnAvant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mav_libelle");

                    b.Property<decimal>("PrixSemaine")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("mav_prixsemaine");

                    b.HasKey("IdMiseEnAvant");

                    b.ToTable("t_e_miseavant_mav", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Modele", b =>
                {
                    b.Property<int>("IdModele")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mod_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdModele"));

                    b.Property<int>("IdMarque")
                        .HasColumnType("integer")
                        .HasColumnName("mar_id");

                    b.Property<string>("LibelleModele")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mod_lib");

                    b.HasKey("IdModele");

                    b.HasIndex("IdMarque");

                    b.ToTable("t_e_modele_mod", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.ModeleBlender", b =>
                {
                    b.Property<int>("IdModeleBlender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mob_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdModeleBlender"));

                    b.Property<string>("Lien")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mob_lien");

                    b.HasKey("IdModeleBlender");

                    b.ToTable("t_e_modeleblender_mob", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Motricite", b =>
                {
                    b.Property<int>("IdMotricite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mot_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMotricite"));

                    b.Property<string>("LibelleMotricite")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mot_lib");

                    b.HasKey("IdMotricite");

                    b.ToTable("t_e_motricite_mot", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.MoyenPaiement", b =>
                {
                    b.Property<int>("IdMoyenPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mop_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMoyenPaiement"));

                    b.Property<string>("TypePaiement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mop_typepaiement");

                    b.HasKey("IdMoyenPaiement");

                    b.ToTable("t_e_moyenpaiement_mop", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("not_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotification"));

                    b.Property<double?>("AncienPrix")
                        .HasColumnType("double precision")
                        .HasColumnName("not_ancien_prix");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_date_creation");

                    b.Property<bool>("EstLue")
                        .HasColumnType("boolean")
                        .HasColumnName("not_est_lue");

                    b.Property<int?>("IdAnnonce")
                        .HasColumnType("integer")
                        .HasColumnName("ann_id");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("not_message");

                    b.Property<double?>("NouveauPrix")
                        .HasColumnType("double precision")
                        .HasColumnName("not_nouveau_prix");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("not_titre");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("not_type");

                    b.Property<string>("UrlNavigation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("not_url_navigation");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdAnnonce");

                    b.HasIndex("IdCompte");

                    b.ToTable("t_e_notification_not", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Offre", b =>
                {
                    b.Property<int>("IdOffre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("off_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOffre"));

                    b.Property<DateTime>("DateOffre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("off_date");

                    b.Property<bool?>("EstAccepte")
                        .HasColumnType("boolean")
                        .HasColumnName("off_estaccepte");

                    b.Property<int>("IdAnnonce")
                        .HasColumnType("integer")
                        .HasColumnName("ann_id");

                    b.Property<int>("IdMessage")
                        .HasColumnType("integer")
                        .HasColumnName("mes_id");

                    b.Property<decimal>("Valeur")
                        .HasColumnType("numeric")
                        .HasColumnName("off_valeur");

                    b.HasKey("IdOffre");

                    b.HasIndex("IdAnnonce");

                    b.HasIndex("IdMessage");

                    b.ToTable("t_e_offre_off", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Pays", b =>
                {
                    b.Property<int>("IdPays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pay_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPays"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pay_libelle");

                    b.HasKey("IdPays");

                    b.ToTable("t_e_pays_pay", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.PieceJointe", b =>
                {
                    b.Property<int>("IdPieceJointe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pj_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPieceJointe"));

                    b.Property<byte[]>("Contenu")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pj_contenu");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pj_date_upload");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pj_extension");

                    b.Property<int>("IdMessage")
                        .HasColumnType("integer")
                        .HasColumnName("mes_id");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pj_nom_fichier");

                    b.Property<long>("TailleFichier")
                        .HasColumnType("bigint")
                        .HasColumnName("pj_taille_fichier");

                    b.Property<string>("TypeMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pj_type_mime");

                    b.HasKey("IdPieceJointe");

                    b.HasIndex("IdMessage");

                    b.ToTable("t_e_piecejointe_pj", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Plainte", b =>
                {
                    b.Property<int>("IdPlainte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pla_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlainte"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pla_date_creation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pla_description");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<int>("IdEtat")
                        .HasColumnType("integer")
                        .HasColumnName("ets_id");

                    b.Property<int>("IdSignalement")
                        .HasColumnType("integer")
                        .HasColumnName("sig_id");

                    b.HasKey("IdPlainte");

                    b.HasIndex("IdCompte");

                    b.HasIndex("IdEtat");

                    b.HasIndex("IdSignalement");

                    b.ToTable("t_e_plainte_pla", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Signalement", b =>
                {
                    b.Property<int>("IdSignalement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sig_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSignalement"));

                    b.Property<DateTime>("DateCreationSignalement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sig_datecreation");

                    b.Property<string>("DescriptionSignalement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sig_description");

                    b.Property<int?>("IdAnnonceSignale")
                        .HasColumnType("integer")
                        .HasColumnName("ann_idannoncesignale");

                    b.Property<int>("IdCompteSignalant")
                        .HasColumnType("integer")
                        .HasColumnName("com_idsignalant");

                    b.Property<int?>("IdCompteSignale")
                        .HasColumnType("integer")
                        .HasColumnName("com_idsignale");

                    b.Property<int>("IdEtatSignalement")
                        .HasColumnType("integer")
                        .HasColumnName("ets_id");

                    b.Property<int>("IdTypeSignalement")
                        .HasColumnType("integer")
                        .HasColumnName("tsi_id");

                    b.HasKey("IdSignalement");

                    b.HasIndex("IdAnnonceSignale");

                    b.HasIndex("IdCompteSignalant");

                    b.HasIndex("IdCompteSignale");

                    b.HasIndex("IdEtatSignalement");

                    b.HasIndex("IdTypeSignalement");

                    b.ToTable("t_e_signalement_sig", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.TokenEmail", b =>
                {
                    b.Property<int>("IdTokenEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tke_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTokenEmail"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("com_email");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tke_expiration");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tke_token");

                    b.Property<string>("TypeToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tke_type");

                    b.Property<bool>("Utilise")
                        .HasColumnType("boolean")
                        .HasColumnName("tke_utilise");

                    b.HasKey("IdTokenEmail");

                    b.HasIndex("IdCompte");

                    b.ToTable("t_e_tokenemail_tke", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.TypeCompte", b =>
                {
                    b.Property<int>("IdTypeCompte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tco_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeCompte"));

                    b.Property<bool>("Cherchable")
                        .HasColumnType("boolean")
                        .HasColumnName("tco_cherchable");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tco_libelle");

                    b.HasKey("IdTypeCompte");

                    b.ToTable("t_e_typecompte_tco", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.TypeJournal", b =>
                {
                    b.Property<int>("IdTypeJournaux")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tjo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeJournaux"));

                    b.Property<string>("LibelleTypeJournaux")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tjo_libelle");

                    b.HasKey("IdTypeJournaux");

                    b.ToTable("t_e_typejournaux_tjo", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.TypeSignalement", b =>
                {
                    b.Property<int>("IdTypeSignalement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tsi_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeSignalement"));

                    b.Property<string>("LibelleTypeSignalement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tsi_libelle");

                    b.HasKey("IdTypeSignalement");

                    b.ToTable("t_e_typesignalement_tsi", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Voiture", b =>
                {
                    b.Property<int>("IdVoiture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("voi_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVoiture"));

                    b.Property<int>("Annee")
                        .HasColumnType("integer")
                        .HasColumnName("voi_annee");

                    b.Property<int>("Couple")
                        .HasColumnType("integer")
                        .HasColumnName("voi_couple");

                    b.Property<double>("CylindrerMoteur")
                        .HasColumnType("double precision")
                        .HasColumnName("voi_cylindrermoteur");

                    b.Property<int>("IdBoiteDeVitesse")
                        .HasColumnType("integer")
                        .HasColumnName("boi_id");

                    b.Property<int>("IdCarburant")
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    b.Property<int>("IdCategorie")
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    b.Property<int>("IdMarque")
                        .HasColumnType("integer")
                        .HasColumnName("mar_id");

                    b.Property<int>("IdModele")
                        .HasColumnType("integer")
                        .HasColumnName("mod_id");

                    b.Property<int?>("IdModeleBlender")
                        .HasColumnType("integer")
                        .HasColumnName("mob_id");

                    b.Property<int>("IdMotricite")
                        .HasColumnType("integer")
                        .HasColumnName("mot_id");

                    b.Property<bool>("InterieurCuire")
                        .HasColumnType("boolean")
                        .HasColumnName("voi_interieurcuire");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("integer")
                        .HasColumnName("voi_kilometrage");

                    b.Property<DateTime>("MiseEnCirculation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voi_miseencirculation");

                    b.Property<int>("NbAirbag")
                        .HasColumnType("integer")
                        .HasColumnName("voi_nbairbag");

                    b.Property<int>("NbCylindres")
                        .HasColumnType("integer")
                        .HasColumnName("voi_nbcylindres");

                    b.Property<int>("NbPlace")
                        .HasColumnType("integer")
                        .HasColumnName("voi_nbplace");

                    b.Property<int>("NbPorte")
                        .HasColumnType("integer")
                        .HasColumnName("voi_nbporte");

                    b.Property<bool>("PositionVolant")
                        .HasColumnType("boolean")
                        .HasColumnName("voi_positionvolant");

                    b.Property<int>("Puissance")
                        .HasColumnType("integer")
                        .HasColumnName("voi_puissance");

                    b.HasKey("IdVoiture");

                    b.HasIndex("IdBoiteDeVitesse");

                    b.HasIndex("IdCarburant");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdMarque");

                    b.HasIndex("IdModele");

                    b.HasIndex("IdModeleBlender");

                    b.HasIndex("IdMotricite");

                    b.ToTable("t_e_voiture_voi", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Vue", b =>
                {
                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<int>("IdAnnonce")
                        .HasColumnType("integer")
                        .HasColumnName("ann_id");

                    b.HasKey("IdCompte", "IdAnnonce");

                    b.HasIndex("IdAnnonce");

                    b.ToTable("t_j_vue_vue", "public");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.APourConversation", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "APourConversationCompteNav")
                        .WithMany("ApourConversations")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Conversation", "APourConversationConversationNav")
                        .WithMany("ApourConversations")
                        .HasForeignKey("IdConversation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("APourConversationCompteNav");

                    b.Navigation("APourConversationConversationNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.APourCouleur", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Couleur", "APourCouleurCouleurNav")
                        .WithMany("APourCouleurs")
                        .HasForeignKey("IdCouleur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Voiture", "APourCouleurVoitureNav")
                        .WithMany("APourCouleurs")
                        .HasForeignKey("IdVoiture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("APourCouleurCouleurNav");

                    b.Navigation("APourCouleurVoitureNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Adresse", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteAdresseNav")
                        .WithMany("Adresses")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Pays", "PaysAdresseNav")
                        .WithMany("Adresses")
                        .HasForeignKey("IdPays")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteAdresseNav");

                    b.Navigation("PaysAdresseNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Annonce", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Adresse", "AdresseAnnonceNav")
                        .WithMany("Annonces")
                        .HasForeignKey("IdAdresse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteAnnonceNav")
                        .WithMany("Annonces")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.EtatAnnonce", "EtatAnnonceNavigation")
                        .WithMany("Annonces")
                        .HasForeignKey("IdEtatAnnonce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.MiseEnAvant", "MiseEnAvantAnnonceNav")
                        .WithMany("Annonces")
                        .HasForeignKey("IdMiseEnAvant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Voiture", "VoitureAnnonceNav")
                        .WithMany("Annonces")
                        .HasForeignKey("IdVoiture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdresseAnnonceNav");

                    b.Navigation("CompteAnnonceNav");

                    b.Navigation("EtatAnnonceNavigation");

                    b.Navigation("MiseEnAvantAnnonceNav");

                    b.Navigation("VoitureAnnonceNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Avis", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Commande", "CommandeAvisNav")
                        .WithMany("AvisListe")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteJugeeNav")
                        .WithMany("AvisJugees")
                        .HasForeignKey("IdJugee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteJugeurNav")
                        .WithMany("AvisJugeur")
                        .HasForeignKey("IdJugeur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommandeAvisNav");

                    b.Navigation("CompteJugeeNav");

                    b.Navigation("CompteJugeurNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Bloque", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteBloquantNav")
                        .WithMany("ComptesBloquants")
                        .HasForeignKey("IdBloquant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteBloqueNav")
                        .WithMany("ComptesBloqueurs")
                        .HasForeignKey("IdBloque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteBloquantNav");

                    b.Navigation("CompteBloqueNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.CarteBancaire", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteCarteBancaireNav")
                        .WithMany("CarteBancaires")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteCarteBancaireNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Commande", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "AcheteurCommande")
                        .WithMany("CommandeAcheteur")
                        .HasForeignKey("IdAcheteur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Annonce", "CommandeAnnonceNav")
                        .WithMany("Commandes")
                        .HasForeignKey("IdAnnonce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.MoyenPaiement", "CommandeMoyenPaiementNav")
                        .WithMany("Commandes")
                        .HasForeignKey("IdMoyenPaiement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "VendeurCommande")
                        .WithMany("CommandeVendeur")
                        .HasForeignKey("IdVendeur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcheteurCommande");

                    b.Navigation("CommandeAnnonceNav");

                    b.Navigation("CommandeMoyenPaiementNav");

                    b.Navigation("VendeurCommande");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Compte", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.EtatCompte", "EtatCompteNav")
                        .WithMany("Comptes")
                        .HasForeignKey("IdEtatCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.TypeCompte", "TypeCompteCompteNav")
                        .WithMany("Comptes")
                        .HasForeignKey("IdTypeCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtatCompteNav");

                    b.Navigation("TypeCompteCompteNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Conversation", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Annonce", "AnnonceConversationNav")
                        .WithMany("Conversations")
                        .HasForeignKey("IdAnnonce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnonceConversationNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Facture", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Commande", "CommandeFactureNav")
                        .WithMany("Factures")
                        .HasForeignKey("IdFacture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommandeFactureNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Favori", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Annonce", "AnnonceFavoriNav")
                        .WithMany("Favoris")
                        .HasForeignKey("IdAnnonce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteFavoriNav")
                        .WithMany("Favoris")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnonceFavoriNav");

                    b.Navigation("CompteFavoriNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Image", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteImageNav")
                        .WithMany("Images")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api_c_sharp.Models.Entity.Voiture", "VoitureImageNav")
                        .WithMany("Images")
                        .HasForeignKey("IdVoiture")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CompteImageNav");

                    b.Navigation("VoitureImageNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Journal", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteJournauxNav")
                        .WithMany("Journaux")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.TypeJournal", "TypeJournauxJournauxNav")
                        .WithMany("Journaux")
                        .HasForeignKey("IdTypeJournal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteJournauxNav");

                    b.Navigation("TypeJournauxJournauxNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Message", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "MessageCompteNav")
                        .WithMany("Messages")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Conversation", "ConversationMessageNav")
                        .WithMany("Messages")
                        .HasForeignKey("IdConversation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationMessageNav");

                    b.Navigation("MessageCompteNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Modele", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Marque", "MarqueModeleNavigation")
                        .WithMany("Modeles")
                        .HasForeignKey("IdMarque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarqueModeleNavigation");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Notification", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Annonce", "AnnonceNotificationNav")
                        .WithMany("Notifications")
                        .HasForeignKey("IdAnnonce");

                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteNotificationNav")
                        .WithMany("Notifications")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnonceNotificationNav");

                    b.Navigation("CompteNotificationNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Offre", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Annonce", "OffreAnnonceNav")
                        .WithMany("Offres")
                        .HasForeignKey("IdAnnonce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Message", "OffreMessageNav")
                        .WithMany("Offres")
                        .HasForeignKey("IdMessage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OffreAnnonceNav");

                    b.Navigation("OffreMessageNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.PieceJointe", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Message", "MessagePjNav")
                        .WithMany("PiecesJointes")
                        .HasForeignKey("IdMessage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessagePjNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Plainte", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "ComptePlainteNav")
                        .WithMany("Plaintes")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.EtatSignalementPlainte", "EtatSignalementPlaintePlainteNav")
                        .WithMany("Plaintes")
                        .HasForeignKey("IdEtat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Signalement", "SignalementPlainteNav")
                        .WithMany("Plaintes")
                        .HasForeignKey("IdSignalement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComptePlainteNav");

                    b.Navigation("EtatSignalementPlaintePlainteNav");

                    b.Navigation("SignalementPlainteNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Signalement", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Annonce", "AnnonceSignaleNav")
                        .WithMany("SignalementsRecus")
                        .HasForeignKey("IdAnnonceSignale");

                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteSignalantNav")
                        .WithMany("SignalementsFaits")
                        .HasForeignKey("IdCompteSignalant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteSignaleNav")
                        .WithMany("SignalementsRecus")
                        .HasForeignKey("IdCompteSignale");

                    b.HasOne("Api_c_sharp.Models.Entity.EtatSignalementPlainte", "EtatSignalementNav")
                        .WithMany("Signalements")
                        .HasForeignKey("IdEtatSignalement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.TypeSignalement", "TypeSignalementSignalementNav")
                        .WithMany("Signalements")
                        .HasForeignKey("IdTypeSignalement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnonceSignaleNav");

                    b.Navigation("CompteSignalantNav");

                    b.Navigation("CompteSignaleNav");

                    b.Navigation("EtatSignalementNav");

                    b.Navigation("TypeSignalementSignalementNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.TokenEmail", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteTokenNav")
                        .WithMany("TokensEmail")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteTokenNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Voiture", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.BoiteDeVitesse", "BoiteVoitureNavigation")
                        .WithMany("Voitures")
                        .HasForeignKey("IdBoiteDeVitesse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Carburant", "CarburantVoitureNavigation")
                        .WithMany("Voitures")
                        .HasForeignKey("IdCarburant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Categorie", "CategorieVoitureNavigation")
                        .WithMany("Voitures")
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Marque", "MarqueVoitureNavigation")
                        .WithMany("Voitures")
                        .HasForeignKey("IdMarque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Modele", "ModeleVoitureNavigation")
                        .WithMany("Voitures")
                        .HasForeignKey("IdModele")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.ModeleBlender", "ModeleBlenderNavigation")
                        .WithMany("Voitures")
                        .HasForeignKey("IdModeleBlender");

                    b.HasOne("Api_c_sharp.Models.Entity.Motricite", "MotriciteVoitureNavigation")
                        .WithMany("Voitures")
                        .HasForeignKey("IdMotricite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoiteVoitureNavigation");

                    b.Navigation("CarburantVoitureNavigation");

                    b.Navigation("CategorieVoitureNavigation");

                    b.Navigation("MarqueVoitureNavigation");

                    b.Navigation("ModeleBlenderNavigation");

                    b.Navigation("ModeleVoitureNavigation");

                    b.Navigation("MotriciteVoitureNavigation");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Vue", b =>
                {
                    b.HasOne("Api_c_sharp.Models.Entity.Annonce", "AnnonceVueNav")
                        .WithMany("Vues")
                        .HasForeignKey("IdAnnonce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_c_sharp.Models.Entity.Compte", "CompteVueNav")
                        .WithMany("Vues")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnonceVueNav");

                    b.Navigation("CompteVueNav");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Adresse", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Annonce", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Conversations");

                    b.Navigation("Favoris");

                    b.Navigation("Notifications");

                    b.Navigation("Offres");

                    b.Navigation("SignalementsRecus");

                    b.Navigation("Vues");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.BoiteDeVitesse", b =>
                {
                    b.Navigation("Voitures");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Carburant", b =>
                {
                    b.Navigation("Voitures");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Categorie", b =>
                {
                    b.Navigation("Voitures");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Commande", b =>
                {
                    b.Navigation("AvisListe");

                    b.Navigation("Factures");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Compte", b =>
                {
                    b.Navigation("Adresses");

                    b.Navigation("Annonces");

                    b.Navigation("ApourConversations");

                    b.Navigation("AvisJugees");

                    b.Navigation("AvisJugeur");

                    b.Navigation("CarteBancaires");

                    b.Navigation("CommandeAcheteur");

                    b.Navigation("CommandeVendeur");

                    b.Navigation("ComptesBloquants");

                    b.Navigation("ComptesBloqueurs");

                    b.Navigation("Favoris");

                    b.Navigation("Images");

                    b.Navigation("Journaux");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Plaintes");

                    b.Navigation("SignalementsFaits");

                    b.Navigation("SignalementsRecus");

                    b.Navigation("TokensEmail");

                    b.Navigation("Vues");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Conversation", b =>
                {
                    b.Navigation("ApourConversations");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Couleur", b =>
                {
                    b.Navigation("APourCouleurs");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.EtatAnnonce", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.EtatCompte", b =>
                {
                    b.Navigation("Comptes");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.EtatSignalementPlainte", b =>
                {
                    b.Navigation("Plaintes");

                    b.Navigation("Signalements");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Marque", b =>
                {
                    b.Navigation("Modeles");

                    b.Navigation("Voitures");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Message", b =>
                {
                    b.Navigation("Offres");

                    b.Navigation("PiecesJointes");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.MiseEnAvant", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Modele", b =>
                {
                    b.Navigation("Voitures");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.ModeleBlender", b =>
                {
                    b.Navigation("Voitures");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Motricite", b =>
                {
                    b.Navigation("Voitures");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.MoyenPaiement", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Pays", b =>
                {
                    b.Navigation("Adresses");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Signalement", b =>
                {
                    b.Navigation("Plaintes");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.TypeCompte", b =>
                {
                    b.Navigation("Comptes");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.TypeJournal", b =>
                {
                    b.Navigation("Journaux");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.TypeSignalement", b =>
                {
                    b.Navigation("Signalements");
                });

            modelBuilder.Entity("Api_c_sharp.Models.Entity.Voiture", b =>
                {
                    b.Navigation("APourCouleurs");

                    b.Navigation("Annonces");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
