name: Deploy API

on:
  push:
    branches:
      - PreProd
    paths:
      - 'Api_c_sharp/Api_c_sharp/**'
      - 'Api_c_sharp/AutoPulse.Shared/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Solution
        run: |
          $solution = Get-ChildItem -Path . -Filter *.sln -Recurse | Select-Object -First 1
          if (-not $solution) { throw "Aucun fichier .sln trouve !" }
          dotnet build $solution.FullName --configuration Release

      - name: Publish API Project
        run: |
          $project = Get-ChildItem -Path . -Filter Api_c_sharp.csproj -Recurse | Select-Object -First 1
          if (-not $project) { throw "Projet Api_c_sharp.csproj introuvable !" }
          dotnet publish $project.FullName -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E29BB569A2E044CEB7A8B15007AB2241 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D38378BA1EC546378BD8627B3ED92D45 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D6F0B3E00CBA4FCFA917304F9ACEC12A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-autopulse'
          package: .