name: Deploy API

on:
  push:
    branches:
      - PreProd
    paths:
      - 'Api_c_sharp/Api_c_sharp/**'
      - 'Api_c_sharp/AutoPulse.Shared/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Solution
        run: |
          $solution = Get-ChildItem -Path . -Filter *.sln -Recurse | Select-Object -First 1
          if (-not $solution) { throw "Aucun fichier .sln trouve !" }
          dotnet build $solution.FullName --configuration Release

      - name: Publish API Project
        run: |
          $project = Get-ChildItem -Path . -Filter Api_c_sharp.csproj -Recurse | Select-Object -First 1
          if (-not $project) { throw "Projet Api_c_sharp.csproj introuvable !" }
          dotnet publish $project.FullName -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98CF53B667C345DDB85390421A8B85BD }} 
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7BE03D1230C84B26AF57F1BCC9BFD50F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_091D1EB795584A6DB7257A0CF181F4FD }}
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-autopulse'
          package: .