name: Deploy Python AI

on:
  push:
    branches:
      - PreProd
    paths:
      - 'Api_Python/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Zip artifact for deployment
        run: |
          cd Api_Python
          # On zip JUSTE le code et le requirements.txt
          # On exclut tout ce qui est lourd ou inutile
          zip -r ../python-app.zip . -x "venv/*" -x ".venv/*" -x "__pycache__/*" -x "*.git*" -x "*.pth" -x "*.pt" -x "*.pkl"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D56B1870F56E4856906EADEBC604F3DE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_60BB171ADA9A4F28B6A9547AF2CD934E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_34457D9CE39D4EDA8F1D08548686D6E7 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'python-autopulse'
          package: ./python-app.zip
          startup-command: 'gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app'
