name: Deploy Blazor Front
on:
  push:
    branches:
      - PreProd
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Build Solution
        run: |
          $solution = Get-ChildItem -Path . -Filter *.sln -Recurse | Select-Object -First 1
          if (-not $solution) { throw "Aucun fichier .sln trouve !" }
          dotnet build $solution.FullName --configuration Release
          
      - name: Publish Blazor Project
        run: |
          $project = Get-ChildItem -Path . -Filter BlazorAutoPulse.csproj -Recurse | Select-Object -First 1
          if (-not $project) { throw "Projet BlazorAutoPulse.csproj introuvable !" }
          dotnet publish $project.FullName -c Release -o "${{env.DOTNET_ROOT}}/myapp" --framework net8.0
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: blazor-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_29490C3EFCAE4DB79706AD541CCA59B9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_11AA53028D1543F4A16DACC535C4CEFB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3A97941F844A4C51B04E1F4A65F70F44 }}
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Azure-Blazor-AutoPulse'
          slot-name: 'Production'
          package: .